CREATE TABLE QUIZ (
    `S_No` NUMERIC(3, 1)
);
INSERT INTO QUIZ VALUES (1.0);
INSERT INTO QUIZ VALUES (2.0);
INSERT INTO QUIZ VALUES (3.0);
INSERT INTO QUIZ VALUES (4.0);
INSERT INTO QUIZ VALUES (5.0);
INSERT INTO QUIZ VALUES (6.0);
INSERT INTO QUIZ VALUES (7.0);
INSERT INTO QUIZ VALUES (8.0);
INSERT INTO QUIZ VALUES (9.0);
INSERT INTO QUIZ VALUES (10.0);
INSERT INTO QUIZ VALUES (11.0);
INSERT INTO QUIZ VALUES (12.0);
INSERT INTO QUIZ VALUES (13.0);
INSERT INTO QUIZ VALUES (14.0);
